### ISSUE TITLE
Command browse_website returned: Error: Message: unknown error: Chrome failed to start: crashed. (unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by Bourn3Dynsty** [Significant-Gravitas/Auto-GPT#1788]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Running autogpt in docker desktop for windows

### Current behavior 😯

 Command browse_website returned: Error: Message: unknown error: Chrome failed to start: crashed. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x5634a2f84fe3 <unknown> #1 0x5634a2cc3d36 <unknown> #2 0x5634a2cecb20 <unknown> #3 0x5634a2ce8a9b <unknown> #4 0x5634a2d2aaf7 <unknown> #5 0x5634a2d2a11f <unknown> #6 0x5634a2d21693 <unknown> #7 0x5634a2cf403a <unknown> #8 0x5634a2cf517e <unknown> #9 0x5634a2f46dbd <unknown> #10 0x5634a2f4ac6c <unknown> #11 0x5634a2f544b0 <unknown> #12 0x5634a2f4bd63 <unknown> #13 0x5634a2f1ec35 <unknown> #14 0x5634a2f6f138 <unknown> #15 0x5634a2f6f2c7 <unknown> #16 0x5634a2f7d093 <unknown> #17 0x7fead9ae1ea7 start_thread

### Expected behavior 🤔

Should be able to read the links it's pulling

### Your prompt 📝

FROM debian:bullseye AS builder

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workdir

RUN apt update && apt -y install git make build-essential

RUN git clone --recursive https://github.com/RediSearch/RediSearch.git

RUN cd RediSearch && make setup && make build

# Use an official Python base image from the Docker Hub
FROM python:3.11-slim

# Switch to root user and install necessary packages
USER root
RUN apt update && apt -y install vim redis-server chromium-driver chromium && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Create a non-root user and set permissions
RUN useradd --create-home appuser
WORKDIR /home/appuser
RUN chown appuser:appuser /home/appuser
USER appuser

# Copy the requirements.txt file and install the requirements
COPY --chown=appuser:appuser requirements-docker.txt .
RUN pip install --no-cache-dir --user -r requirements-docker.txt

# Copy the application files
COPY --chown=appuser:appuser autogpt/ ./autogpt

# Set the entrypoint
ENTRYPOINT ["python", "-m", "autogpt"]

**Comment by jik-ai** [comment]
I got this to work in docker by making the following patches to the dockerfile and web.py

https://github.com/Significant-Gravitas/Auto-GPT/commit/414bd4caf130cc7a7ba9d365e6ed2a903c0bfb98

I would PR this but will probably break non-docker versions.

**Comment by Bourn3Dynsty** [comment]
That indeed work but it yielded a new error : Command browse_website returned: Error: Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed (Session info: headless chrome=112.0.5615.121) Stacktrace: #0 0x5612c2c8bfe3 <unknown> #1 0x5612c29cabc1 <unknown> #2 0x5612c29b4ad2 <unknown> #3 0x5612c29b3608 <unknown> #4 0x5612c29b3db2 <unknown> #5 0x5612c29c1283 <unknown> #6 0x5612c29c22c2 <unknown> #7 0x5612c29d24db <unknown> #8 0x5612c29d64eb <unknown> #9 0x5612c29b4273 <unknown> #10 0x5612c29d2108 <unknown> #11 0x5612c2a41140 <unknown> #12 0x5612c2a28693 <unknown> #13 0x5612c29fb03a <unknown> #14 0x5612c29fc17e <unknown> #15 0x5612c2c4ddbd <unknown> #16 0x5612c2c51c6c <unknown> #17 0x5612c2c5b4b0 <unknown> #18 0x5612c2c52d63 <unknown> #19 0x5612c2c25c35 <unknown> #20 0x5612c2c76138 <unknown> #21 0x5612c2c762c7 <unknown> #22 0x5612c2c84093 <unknown> #23 0x7eff5e8b2ea7 start_thread

**Comment by jik-ai** [comment]
I also ran into this occasionally, I assumed due to a memory issue, but try with some other domains to narrow down?

**Comment by dexchaindev** [comment]
I added this to web_selenium.py to fix it:
    # Add the following lines:
    options.add_argument("--no-sandbox")
    options.add_argument("--headless")
    options.add_argument("--disable-dev-shm-usage")

**Comment by jamie7893** [comment]
> 

works great, thanks

**Comment by Pwuts** [comment]
Resolved in #1473

**Comment by bjm88** [comment]
I saw this today on the 0.2.2 latest stable.  The weird thing is AutoGPT previously worked hours early and was able to launch chrome (I think, unless it fell back to google search api directly?).  Anything else to check...Using standard MacBook pro latest OS, docker fully updated, run as docker compose container.....?

SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited abnormally. (chrome not reachable) (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x0040006e6fe3 <unknown> #1 0x004000425d36 <unknown> #2 0x00400044eb20 <unknown> #3 0x00400044aa9b <unknown> #4 0x00400048caf7 <unknown> #5 0x00400048c11f <unknown> #6 0x004000483693 <unknown> #7 0x00400045603a <unknown> #8 0x00400045717e <unknown> #9 0x0040006a8dbd <unknown> #10 0x0040006acc6c <unknown> #11 0x0040006b64b0 <unknown> #12 0x0040006add63 <unknown> #13 0x004000680c35 <unknown> #14 0x0040006d1138 <unknown> #15 0x0040006d12c7 <unknown> #16 0x0040006df093 <unknown> #17 0x004002585ea7 start_thread
 THOUGHTS:  Since the browse_website command failed, I will try using the Google Search command

**Comment by d3fc0n2008** [comment]
> I added this to web_selenium.py to fix it: # Add the following lines: options.add_argument("--no-sandbox") options.add_argument("--headless") options.add_argument("--disable-dev-shm-usage")

Can you tell me exactly where you added this in the code?  I'm really new to all of this

**Comment by rudolfovic** [comment]
```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://somesite.com/', 'question': 'water pump'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
[WDM] - Downloading: 19.2kB [00:00, 6.00MB/s]
[WDM] - Downloading: 19.2kB [00:00, 3.64MB/s]
[WDM] - Downloading: 100%|████████████████████████████████████████████████████████████████████████| 2.93M/2.93M [00:01<00:00, 2.11MB/s]
SYSTEM:  Command browse_website returned: Error: Message: Process unexpectedly closed with status 1
 THOUGHTS:  It seems like there was an error with the 'browse_website' command. I suggest we use the 'google' command to search for a water pump instead.
```
None of the browsers work for me, neither through docker nor vanilla macOS. I don't get why it wouldn't work through docker, isn't it supposed to perfectly replicate the intended environment?

When run on macOS directly with safari, a window actually opens (since Safari doesn't support headless) and the page is rendered but there is still an error within Augo-GPT.

**Comment by sumukhshetty** [comment]
> d3fc0n2008

I took a bit to figure this out but if you're using docker - you cannot edit the image.

You will have to clone the github repo - like so git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git

You then need to make a few edits on the dockerfile in this repo.

Then you can create a docker build on the file - and if you run that docker image - it should fix the issue

I also found this specific comment useful to fix the issue - https://github.com/Significant-Gravitas/Auto-GPT/issues/2600#issuecomment-1528943018 

I think the issue only exists for people who are running the M1 chips

**Comment by rudolfovic** [comment]
I am running on Apple Silicon and the fix helped, thanks so much!

**Comment by matguest** [comment]
I changed the default browser to Firefox by editing the .env file and it work -> USE_WEB_BROWSER=firefox

**Comment by pareekyashovardhan** [comment]
> I changed the default browser to Firefox by editing the .env file and it work -> USE_WEB_BROWSER=firefox

You are a low key genius my friend! This helped a lot, thanks.

**Comment by lahfir** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/3432#issuecomment-1534955357
