### ISSUE TITLE
USB memory

### ISSUE THREAD

**Issue by ishaoshupai** [Significant-Gravitas/Auto-GPT#1949]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

DevTools listening on ws://127.0.0.1:61674/devtools/browser/7bbf6236-bfa6-4f13-bd91-f3369a31e998
Text length: 36792 characters
Adding chunk 1 / 5 to memory
Summarizing chunk 1 / 5
[4912:3656:0416/200146.913:ERROR:device_event_log_impl.cc(222)] [20:01:46.920] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[4912:3656:0416/200146.920:ERROR:device_event_log_impl.cc(222)] [20:01:46.922] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
Added chunk 1 summary to memory
Adding chunk 2 / 5 to memory
Summarizing chunk 2 / 5
Added chunk 2 summary to memory
Adding chunk 3 / 5 to memory
Summarizing chunk 3 / 5
Added chunk 3 summary to memory
Adding chunk 4 / 5 to memory
Summarizing chunk 4 / 5
Added chunk 4 summary to memory
Adding chunk 5 / 5 to memory
Summarizing chunk 5 / 5
Added chunk 5 summary to memory

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Nickonomic** [comment]
+

**Comment by Z-Ai-c** [comment]
i also get a similar issue, if i see it again ill past the output here for the devs

**Comment by Z-Ai-c** [comment]
![WindowsTerminal_IRxH3zwhNQ](https://user-images.githubusercontent.com/130925500/232333583-672cabe8-a2c9-484c-bf4b-61593c2e4d03.png)

**Comment by Alexys007** [comment]
Same here:

DevTools listening on ws://127.0.0.1:51559/devtools/browser/851f38da-62f0-41c5-8822-e614bf2e7392
Text length: 12730 characters
Adding chunk 1 / 2 to memory
Summarizing chunk 1 / 2
[26860:23844:0416/183129.265:ERROR:device_event_log_impl.cc(222)] [18:31:29.264] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Added chunk 1 summary to memory
Adding chunk 2 / 2 to memory
Summarizing chunk 2 / 2
Added chunk 2 summary to memory
Summarized 2 chunks.

Windows 11: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.30 GHz
32,0 GB (31,8 GB usable)

**Comment by richbeales** [comment]
I also see this.  It doesn't seem to affect the operation of the program however

**Comment by ltinerary** [comment]
[In Stackoverflow, I Found a discussion of this issue](https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connectio)

> It all started with the reporting of chromium issue [Remove WebUSB's dependency on libusb on Windows](https://bugs.chromium.org/p/chromium/issues/detail?id=637404) as:
> 
> For Linux (probably Mac as well), both WebUSB notification and communication works correctly (after allowing user access to the device in udev rules).
> For Windows, it seems that libusb only works with a non-standard WinUsb driver (https://github.com/libusb/libusb/issues/255).

And，I also try 
```python
options.add_experimental_option('excludeSwitches', ['enable-logging'])
```
to  supressed from appearing on the console,
![image](https://user-images.githubusercontent.com/79144923/233242869-82a9ecd4-a135-4e87-95f7-d501faee69f3.png)

These logs no longer appear.

**Comment by ltinerary** [comment]
Looks like this issue was solved By this commit #https://github.com/Significant-Gravitas/Auto-GPT/commit/085842d43c76d65739f063764f06279df641e031

**Comment by Li1177** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Steps to reproduce 🕹
> DevTools listening on ws://127.0.0.1:61674/devtools/browser/7bbf6236-bfa6-4f13-bd91-f3369a31e998 Text length: 36792 characters Adding chunk 1 / 5 to memory Summarizing chunk 1 / 5 [4912:3656:0416/200146.913:ERROR:device_event_log_impl.cc(222)] [20:01:46.920] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F) [4912:3656:0416/200146.920:ERROR:device_event_log_impl.cc(222)] [20:01:46.922] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F) Added chunk 1 summary to memory Adding chunk 2 / 5 to memory Summarizing chunk 2 / 5 Added chunk 2 summary to memory Adding chunk 3 / 5 to memory Summarizing chunk 3 / 5 Added chunk 3 summary to memory Adding chunk 4 / 5 to memory Summarizing chunk 4 / 5 Added chunk 4 summary to memory Adding chunk 5 / 5 to memory Summarizing chunk 5 / 5 Added chunk 5 summary to memory
> 
> ### Current behavior 😯
> _No response_
> 
> ### Expected behavior 🤔
> _No response_
> 
> ### Your prompt 📝
> ```yaml
> # Paste your prompt here
> ```

Update to 2.2 will be fine

**Comment by ntindle** [comment]
Fixed?

**Comment by Xeta6** [comment]
> > ### Duplicates
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Steps to reproduce 🕹
> > DevTools listening on ws://127.0.0.1:61674/devtools/browser/7bbf6236-bfa6-4f13-bd91-f3369a31e998 Text length: 36792 characters Adding chunk 1 / 5 to memory Summarizing chunk 1 / 5 [4912:3656:0416/200146.913:ERROR:device_event_log_impl.cc(222)] [20:01:46.920] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F) [4912:3656:0416/200146.920:ERROR:device_event_log_impl.cc(222)] [20:01:46.922] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F) Added chunk 1 summary to memory Adding chunk 2 / 5 to memory Summarizing chunk 2 / 5 Added chunk 2 summary to memory Adding chunk 3 / 5 to memory Summarizing chunk 3 / 5 Added chunk 3 summary to memory Adding chunk 4 / 5 to memory Summarizing chunk 4 / 5 Added chunk 4 summary to memory Adding chunk 5 / 5 to memory Summarizing chunk 5 / 5 Added chunk 5 summary to memory
> > ### Current behavior 😯
> > _No response_
> > ### Expected behavior 🤔
> > _No response_
> > ### Your prompt 📝
> > ```yaml
> > # Paste your prompt here
> > ```
> 
> Update to 2.2 will be fine

Wait what needs to be updated to 2.2? A specific file? Sorry, I'm a bit new to this.

**Comment by ltinerary** [comment]
@Xeta6 

https://github.com/Significant-Gravitas/Auto-GPT/releases/tag/v0.2.2

**Comment by lyncker** [comment]
I updated to 2.2 but the error persists ...

**Comment by LeRobert** [comment]
It originates in the Selenium web driver used for parsing websites. This error persists also in the 0.3.0 version.
It should be benign, though (https://stackoverflow.com/questions/64927909/failed-to-read-descriptor-from-node-connection-a-device-attached-to-the-system)

**Comment by anonhostpi** [comment]
@ntindle, I don't see anywhere in the source code where that excludeSwitch was toggled. I don't think that this was fixed.

@LeRobert is correct about what the error is. This also applies to #1636

Here is another SO question referencing the issue: https://stackoverflow.com/questions/75160044/how-do-i-resolve-this-error-in-selenium-error-couldnt-read-tbscertificate-as
